version: '3'
services:
  php:
    container_name: php
    image: 'a2media/bedrock:php'
    hostname: dev.local
    depends_on:
      - db
    links:
      - db
    networks:
      - php
      - db
#    volumes:
#      - app:/var/www
    env_file:
      - ./data/env/development/.env
      - ./data/env/development/.env.mariadb
    command: /bin/sh -c "php-fpm -F"
    ports:
      - 222:22/tcp
  nginx:
    container_name: nginx
    image: 'a2media/bedrock:nginx'
    depends_on:
      - php
    links:
      - php
    volumes_from:
      - php
#    volumes:
#      - ./storage/web:/data
    networks:
      - php
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Jakarta
      - BEDROCK_FASTCGI_PASS=php:9000
  db:
    tty: true
    image: 'amd64/mariadb'
    restart: unless-stopped
    networks:
      - db
    volumes:
      - ./data/config/mysql.cnf:/etc/mysql/my.cnf
      - db:/var/lib/mysql
    env_file:
      - ./data/env/development/.env.mariadb
networks:
  php:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
  db:
    driver_opts:
      com.docker.network.enable_ipv6: "false"
volumes:
  db:
  php:
  nginx:
